<a href="https://colab.research.google.com/github/eunseochu/YB_4th/blob/main/100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
pip install generators

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for generators: filename=generators-2020.4.27-py3-none-any.whl size=42882 sha256=720d7d3c923e22e1edc837e90f8b711d88b662b0d96b5d7cfb9d19585b9f85e6
  Stored in directory: /root/.cache/pip/wheels/9a/7b/dd/e9a917bf0ec0efb75a88aa51cf3703d8f40f51e77529e58289
  Created wheel for strict-functions: filename=strict_functions-2020.2.4-py3-none-any.whl size=15476 sha256=001dc02d697b448d7dac9c84a5aee0b540e69cdaeaedd45d8ccc9833c8efce97
  Stored in directory: /root/.cache/pip/wheels/21/7a/3c/10008c3e5a4821310b91420fcb14fa3b957cb5c8ca4d506fff
Successfully built generators strict-functions


In [ ]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
array1 = np.zeros(10)

print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [7]:
print('%d bytes' %(array1.size * array1.itemsize))

80 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
array2 = np.zeros(10)
array2[4] = 1

print(array2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
array3 = np.arange(start = 10, stop = 50)

print(array3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
array3_desc = np.sort(array3)[::-1]

print(array3_desc)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
array4 = np.arange(start = 0, stop = 9)
array4_2 = array4.reshape(3, 3)

print(array4_2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array5 = np.array([1, 2, 0, 0, 4, 0])

print(np.nonzero(array5))

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
array6 = np.identity(3) # np.eye

print(array6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
array7 = np.random.random((3, 3, 3))

print(array7)

[[[0.29750361 0.65418375 0.1538434 ]
  [0.88708982 0.94186276 0.88102064]
  [0.34795332 0.8276092  0.96766074]]

 [[0.63293414 0.82485842 0.40725223]
  [0.83545824 0.06047611 0.43751884]
  [0.64109858 0.06070451 0.84086329]]

 [[0.19411117 0.80903549 0.22723528]
  [0.29308365 0.84224298 0.0762566 ]
  [0.52925753 0.74559992 0.60193002]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [9]:
array8 = np.random.random((10, 10))
print(array8)

array8_min = array8.min()
array8_max = array8.max()

print(array8_min, array8_max)

[[0.18537891 0.50039054 0.83071272 0.0913357  0.49962899 0.44629341
  0.703859   0.63499693 0.09394731 0.13792351]
 [0.54120224 0.52248585 0.91840029 0.30675602 0.37418206 0.1131011
  0.77533491 0.75396152 0.26415489 0.0060352 ]
 [0.38571423 0.67161152 0.67386142 0.37658067 0.00354892 0.02968708
  0.49068664 0.36899028 0.87130412 0.78266925]
 [0.11501612 0.84501756 0.8423127  0.63227965 0.38678076 0.14567836
  0.22331603 0.40955804 0.88175367 0.68877569]
 [0.89513553 0.76295468 0.06921994 0.01527007 0.7360445  0.05804107
  0.87899096 0.10649307 0.9026417  0.24525612]
 [0.36724829 0.31050492 0.44139166 0.93430413 0.7414467  0.75361688
  0.92553287 0.13705514 0.84720912 0.81479383]
 [0.48793716 0.04653538 0.27320199 0.69049703 0.47021382 0.48857129
  0.90648577 0.51171166 0.75652932 0.09335637]
 [0.55799665 0.67846227 0.62935876 0.3358456  0.6312708  0.88698152
  0.99263394 0.23920103 0.76012359 0.29451825]
 [0.06151199 0.60142837 0.48483325 0.96421046 0.00889302 0.70790956
  0.62675462 

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
array9 = np.random.random(30)
print(array9)

array9_mean = array9.mean()
print(array9_mean)

[0.42964008 0.05888854 0.52937699 0.40053336 0.95991471 0.26942662
 0.10664021 0.18763458 0.89600759 0.6517116  0.65971164 0.93784903
 0.64617016 0.64372816 0.28312873 0.73276089 0.67200882 0.06665307
 0.25296686 0.89982961 0.58454881 0.78027972 0.88044479 0.73843851
 0.75983069 0.44493854 0.63719352 0.79612755 0.08070417 0.51628773]
0.5501125095810872


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array10 = np.ones((5, 5))
array10[1:-1, 1:-1] = 0

print(array10)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan

nan

In [ ]:
np.nan == np.nan # np.nan = 정의할 수 없는 숫자

False

In [ ]:
np.inf > np.nan # np.inf = 무한대 표현

False

In [ ]:
np.nan - np.nan

nan

In [ ]:
np.nan in set([np.nan])

True

In [ ]:
0.3 == 3 * 0.1

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
array11 = np.diag(np.arange(start = 1, stop = 5), k = -1)

print(array11)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
array12 = np.zeros((8, 8), dtype = int)
array12[1::2, ::2] = 1
array12[::2 , 1::2] = 1

print(array12)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [10]:
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
array13 = np.random.random((5, 5))
array13 = (array13 - np.mean(array13) / np.std(array13))

print(array13)

[[-1.86867948 -1.15424081 -1.22929277 -1.72581528 -1.50578186]
 [-1.29576779 -1.51534847 -1.41113545 -1.58092623 -1.25614095]
 [-1.02989483 -1.22632295 -1.72316777 -0.95544701 -1.12241801]
 [-1.56540325 -1.84384096 -1.62778919 -1.09290676 -1.53211084]
 [-1.27407055 -1.71224862 -1.49135971 -1.58248112 -1.08187714]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [11]:
color = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
array14 = np.dot(np.ones((5, 3)), np.ones((3, 2)))

print(array14)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array15 = np.arange(11)
array15[(3 < array15) & (array15 < 8)] *= -1

print(array15)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(11)

print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
Z**Z

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
       10000000000])

In [ ]:
2 << Z >> 2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

In [ ]:
Z <- Z

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [ ]:
1j*Z

array([0. +0.j, 0. +1.j, 0. +2.j, 0. +3.j, 0. +4.j, 0. +5.j, 0. +6.j,
       0. +7.j, 0. +8.j, 0. +9.j, 0.+10.j])

In [ ]:
Z/1/1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
Z<Z>Z

ValueError: ignored

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [12]:
np.array(0) / np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [13]:
np.array(0) // np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [14]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [19]:
array15 = np.random.randint(0,10,10)
array16 = np.random.randint(0,10,10)

print(np.intersect1d(array15, array16))

[0 2 3 6 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [17]:
np.sqrt(-1) == np.emath.sqrt(-1) # False

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [18]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [20]:
array17 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

print(array17)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [21]:
array18 = np.ones(3)*1
array19 = np.ones(3)*2
np.add(array18, array19, out = array19)
np.divide(array18, 2, out = array18)
np.negative(array18, out = array18)
np.multiply(array18, array19, out = array18)

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [22]:
array20 = np.random.uniform(0,10,10)

print(array20 - array20%1)
print(array20 // 1)
print(np.floor(array20))
print(array20.astype(int))
print(np.trunc(array20))

[2. 7. 6. 5. 6. 3. 6. 6. 3. 0.]
[2. 7. 6. 5. 6. 3. 6. 6. 3. 0.]
[2. 7. 6. 5. 6. 3. 6. 6. 3. 0.]
[2 7 6 5 6 3 6 6 3 0]
[2. 7. 6. 5. 6. 3. 6. 6. 3. 0.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [24]:
array21 = np.zeros((5,5))
array21 += np.arange(5)

print(array21)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [25]:
array22 = np.random.random(10)
array22.sort()

print(array22)

[0.01822756 0.04780882 0.12063183 0.49161512 0.58535994 0.59529461
 0.60527011 0.68523197 0.71541485 0.94178732]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [27]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.array_equal(A,B)
print(equal)

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [29]:
array23 = np.random.random((10,2))
X,Y = array23[:,0], array23[:,1]
array24 = np.sqrt(X**2+Y**2)
array25 = np.arctan2(Y,X)

print(array24)
print(array25)

[0.52801788 0.7438611  0.84614163 0.79416204 0.69335148 0.25589444
 0.75912579 1.06987265 0.76430527 0.66119165]
[1.44849761 1.30334798 0.72013703 0.99272152 1.37131611 0.25775786
 0.49113404 0.690959   1.28896195 0.24920389]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [31]:
array26 = np.random.random(10)
array26[array26.argmax()] = 0

print(array26)

[0.09860897 0.14059572 0.70028407 0.89067782 0.86064258 0.07632447
 0.01697566 0.02393488 0.         0.88800266]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [32]:
Z = np.arange(100)
v = np.random.uniform(0,100)

index = (np.abs(Z-v)).argmin()
print(Z[index])

2


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [33]:
array27 = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(array27):
    print(index, value)

for index in np.ndindex(array27.shape):
    print(index, array27[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [34]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [37]:
array28 = np.random.randint(0,10,(3,3))

print(array28)
print(array28[array28[:,1].argsort()])

[[5 3 4]
 [4 3 8]
 [9 6 1]]
[[5 3 4]
 [4 3 8]
 [9 6 1]]
